const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Behaviors.scrollto,
		C3.Plugins.Text,
		C3.Behaviors.Anchor,
		C3.Plugins.TextBox,
		C3.Plugins.TiledBg,
		C3.Behaviors.Fade,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.AJAX,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Particles.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.TextBox.Acts.SetCSSStyle,
		C3.Plugins.TextBox.Cnds.CompareText,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.TextBox.Cnds.OnTextChanged,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Arr.Exps.Height,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.TextBox.Exps.Text,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.Else
	];
};
self.C3_JsPropNameTable = [
	{var: 0},
	{Sine: 0},
	{MoveTo: 0},
	{startLogo: 0},
	{ScrollTo: 0},
	{startLogoShadow: 0},
	{logiks: 0},
	{scoreText: 0},
	{Anchor: 0},
	{logo: 0},
	{nameText: 0},
	{Text: 0},
	{loginInput: 0},
	{passwordInput: 0},
	{loginButton: 0},
	{justText: 0},
	{Fade: 0},
	{TiledBackground: 0},
	{Touch: 0},
	{Array: 0},
	{AJAX: 0},
	{Particles: 0},
	{course: 0},
	{icon: 0},
	{last: 0},
	{i: 0}
];

self.InstanceType = {
	startLogo: class extends self.ISpriteInstance {},
	startLogoShadow: class extends self.ISpriteInstance {},
	logiks: class extends self.ISpriteInstance {},
	scoreText: class extends self.ITextInstance {},
	logo: class extends self.ISpriteInstance {},
	nameText: class extends self.ITextInstance {},
	Text: class extends self.ITextInstance {},
	loginInput: class extends self.ITextInputInstance {},
	passwordInput: class extends self.ITextInputInstance {},
	loginButton: class extends self.ISpriteInstance {},
	justText: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Touch: class extends self.IInstance {},
	Array: class extends self.IArrayInstance {},
	AJAX: class extends self.IInstance {},
	Particles: class extends self.IParticlesInstance {},
	course: class extends self.ITextInstance {},
	icon: class extends self.ISpriteInstance {},
	last: class extends self.ITextInstance {}
}